### ISSUE TITLE
[JOSS review] Make test/example file accessible from the package

### ISSUE THREAD

**Issue by stella-bourdin** [daniloceano/CycloPhaser#39]
Hello,
This issue arises from the JOSS review ongoing here: https://github.com/openjournals/joss-reviews/issues/7363

It would be helpful if the example csv file in `tests/test.csv` could be accessed as `cyclophaser.example_file`or something similar. 
In the current state of things, the example script in https://cyclophaser.readthedocs.io/en/latest/usage.html cannot be run without first downloading the file in one's own folder, or changing the path to the installation path of the package. 

One way to do so is to add something alike the below in `__init__.py`:
```
import pathlib
here = pathlib.Path(__file__).parent
testdata_dir = here / "example_data"
example_file = str(testdata_dir / "test.csv")
```

Another way is to look into `pkg_resources`.

**Comment by daniloceano** [comment]
Hi @stella-bourdin,

Thank you for your suggestion! We’ve updated the package to include the example CSV file, now named example_file.csv, which can be accessed directly via the package as cyclophaser.example_file. This way, users won’t need to manually download or adjust the path. We’ve also updated setup.py to include the example_file.csv in the package data and adjusted __init__.py accordingly.

Feel free to try it out, and let us know if you have any further feedback!

Best regards,
Danilo

**Comment by stella-bourdin** [comment]
Hi, I can confirm this is now functionnal.
